[package]
name = "strings"
version = "0.1.0"
authors = ["Henry Eklind <henry@karlek.io>"]
edition = "2018"

[dependencies]
futures = "0.1.26"
grpcio = "0.4"
protobuf = "2.8.1" # grpcio
log = "0.4.7"
directories = "2.0.1"
lazy_static = "1.3.0"
regex = "1.2.0"
