# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: disasm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bin_pb2 as bin__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='disasm.proto',
  package='disasm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x64isasm.proto\x12\x06\x64isasm\x1a\tbin.proto\"$\n\x12\x44isassembleRequest\x12\x0e\n\x06\x62in_id\x18\x01 \x01(\t\"E\n\x10\x44isassembleReply\x12\x31\n\rexec_sections\x18\x01 \x03(\x0b\x32\x1a.disasm.DisassembleSection\"J\n\x12\x44isassembleSection\x12\x1d\n\x07section\x18\x01 \x01(\x0b\x32\x0c.bin.Section\x12\x15\n\rvalid_offsets\x18\x02 \x03(\x04\x32U\n\x0c\x44isassembler\x12\x45\n\x0b\x44isassemble\x12\x1a.disasm.DisassembleRequest\x1a\x18.disasm.DisassembleReply\"\x00\x62\x06proto3')
  ,
  dependencies=[bin__pb2.DESCRIPTOR,])




_DISASSEMBLEREQUEST = _descriptor.Descriptor(
  name='DisassembleRequest',
  full_name='disasm.DisassembleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bin_id', full_name='disasm.DisassembleRequest.bin_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=71,
)


_DISASSEMBLEREPLY = _descriptor.Descriptor(
  name='DisassembleReply',
  full_name='disasm.DisassembleReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exec_sections', full_name='disasm.DisassembleReply.exec_sections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=142,
)


_DISASSEMBLESECTION = _descriptor.Descriptor(
  name='DisassembleSection',
  full_name='disasm.DisassembleSection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='section', full_name='disasm.DisassembleSection.section', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_offsets', full_name='disasm.DisassembleSection.valid_offsets', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=218,
)

_DISASSEMBLEREPLY.fields_by_name['exec_sections'].message_type = _DISASSEMBLESECTION
_DISASSEMBLESECTION.fields_by_name['section'].message_type = bin__pb2._SECTION
DESCRIPTOR.message_types_by_name['DisassembleRequest'] = _DISASSEMBLEREQUEST
DESCRIPTOR.message_types_by_name['DisassembleReply'] = _DISASSEMBLEREPLY
DESCRIPTOR.message_types_by_name['DisassembleSection'] = _DISASSEMBLESECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DisassembleRequest = _reflection.GeneratedProtocolMessageType('DisassembleRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISASSEMBLEREQUEST,
  '__module__' : 'disasm_pb2'
  # @@protoc_insertion_point(class_scope:disasm.DisassembleRequest)
  })
_sym_db.RegisterMessage(DisassembleRequest)

DisassembleReply = _reflection.GeneratedProtocolMessageType('DisassembleReply', (_message.Message,), {
  'DESCRIPTOR' : _DISASSEMBLEREPLY,
  '__module__' : 'disasm_pb2'
  # @@protoc_insertion_point(class_scope:disasm.DisassembleReply)
  })
_sym_db.RegisterMessage(DisassembleReply)

DisassembleSection = _reflection.GeneratedProtocolMessageType('DisassembleSection', (_message.Message,), {
  'DESCRIPTOR' : _DISASSEMBLESECTION,
  '__module__' : 'disasm_pb2'
  # @@protoc_insertion_point(class_scope:disasm.DisassembleSection)
  })
_sym_db.RegisterMessage(DisassembleSection)



_DISASSEMBLER = _descriptor.ServiceDescriptor(
  name='Disassembler',
  full_name='disasm.Disassembler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=220,
  serialized_end=305,
  methods=[
  _descriptor.MethodDescriptor(
    name='Disassemble',
    full_name='disasm.Disassembler.Disassemble',
    index=0,
    containing_service=None,
    input_type=_DISASSEMBLEREQUEST,
    output_type=_DISASSEMBLEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISASSEMBLER)

DESCRIPTOR.services_by_name['Disassembler'] = _DISASSEMBLER

# @@protoc_insertion_point(module_scope)
