# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import disasm_pb2 as disasm__pb2


class DisassemblerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Disassemble = channel.unary_unary(
        '/disasm.Disassembler/Disassemble',
        request_serializer=disasm__pb2.DisassembleRequest.SerializeToString,
        response_deserializer=disasm__pb2.DisassembleReply.FromString,
        )


class DisassemblerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Disassemble(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DisassemblerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Disassemble': grpc.unary_unary_rpc_method_handler(
          servicer.Disassemble,
          request_deserializer=disasm__pb2.DisassembleRequest.FromString,
          response_serializer=disasm__pb2.DisassembleReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'disasm.Disassembler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
