# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='strings.proto',
  package='strings',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rstrings.proto\x12\x07strings\"\"\n\x0eStringsRequest\x12\x10\n\x08\x65lf_path\x18\x01 \x01(\t\"2\n\nStringInfo\x12\x10\n\x08location\x18\x01 \x01(\x04\x12\x12\n\nraw_string\x18\x02 \x01(\t\"4\n\x0cStringsReply\x12$\n\x07strings\x18\x01 \x03(\x0b\x32\x13.strings.StringInfo2V\n\x10StringsExtractor\x12\x42\n\x0e\x45xtractStrings\x12\x17.strings.StringsRequest\x1a\x15.strings.StringsReply\"\x00\x62\x06proto3')
)




_STRINGSREQUEST = _descriptor.Descriptor(
  name='StringsRequest',
  full_name='strings.StringsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elf_path', full_name='strings.StringsRequest.elf_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_STRINGINFO = _descriptor.Descriptor(
  name='StringInfo',
  full_name='strings.StringInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='strings.StringInfo.location', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_string', full_name='strings.StringInfo.raw_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=112,
)


_STRINGSREPLY = _descriptor.Descriptor(
  name='StringsReply',
  full_name='strings.StringsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strings', full_name='strings.StringsReply.strings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=166,
)

_STRINGSREPLY.fields_by_name['strings'].message_type = _STRINGINFO
DESCRIPTOR.message_types_by_name['StringsRequest'] = _STRINGSREQUEST
DESCRIPTOR.message_types_by_name['StringInfo'] = _STRINGINFO
DESCRIPTOR.message_types_by_name['StringsReply'] = _STRINGSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringsRequest = _reflection.GeneratedProtocolMessageType('StringsRequest', (_message.Message,), {
  'DESCRIPTOR' : _STRINGSREQUEST,
  '__module__' : 'strings_pb2'
  # @@protoc_insertion_point(class_scope:strings.StringsRequest)
  })
_sym_db.RegisterMessage(StringsRequest)

StringInfo = _reflection.GeneratedProtocolMessageType('StringInfo', (_message.Message,), {
  'DESCRIPTOR' : _STRINGINFO,
  '__module__' : 'strings_pb2'
  # @@protoc_insertion_point(class_scope:strings.StringInfo)
  })
_sym_db.RegisterMessage(StringInfo)

StringsReply = _reflection.GeneratedProtocolMessageType('StringsReply', (_message.Message,), {
  'DESCRIPTOR' : _STRINGSREPLY,
  '__module__' : 'strings_pb2'
  # @@protoc_insertion_point(class_scope:strings.StringsReply)
  })
_sym_db.RegisterMessage(StringsReply)



_STRINGSEXTRACTOR = _descriptor.ServiceDescriptor(
  name='StringsExtractor',
  full_name='strings.StringsExtractor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=168,
  serialized_end=254,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExtractStrings',
    full_name='strings.StringsExtractor.ExtractStrings',
    index=0,
    containing_service=None,
    input_type=_STRINGSREQUEST,
    output_type=_STRINGSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STRINGSEXTRACTOR)

DESCRIPTOR.services_by_name['StringsExtractor'] = _STRINGSEXTRACTOR

# @@protoc_insertion_point(module_scope)
