# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import strings_pb2 as strings__pb2


class StringsExtractorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExtractStrings = channel.unary_unary(
        '/strings.StringsExtractor/ExtractStrings',
        request_serializer=strings__pb2.StringsRequest.SerializeToString,
        response_deserializer=strings__pb2.StringsReply.FromString,
        )


class StringsExtractorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExtractStrings(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StringsExtractorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExtractStrings': grpc.unary_unary_rpc_method_handler(
          servicer.ExtractStrings,
          request_deserializer=strings__pb2.StringsRequest.FromString,
          response_serializer=strings__pb2.StringsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'strings.StringsExtractor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
