# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upload.proto',
  package='upload',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cupload.proto\x12\x06upload\"@\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"\x19\n\x0bUploadReply\x12\n\n\x02id\x18\x01 \x01(\t2@\n\x06Upload\x12\x36\n\x06Upload\x12\x15.upload.UploadRequest\x1a\x13.upload.UploadReply\"\x00\x62\x06proto3')
)




_UPLOADREQUEST = _descriptor.Descriptor(
  name='UploadRequest',
  full_name='upload.UploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='upload.UploadRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='upload.UploadRequest.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='upload.UploadRequest.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=88,
)


_UPLOADREPLY = _descriptor.Descriptor(
  name='UploadReply',
  full_name='upload.UploadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='upload.UploadReply.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['UploadRequest'] = _UPLOADREQUEST
DESCRIPTOR.message_types_by_name['UploadReply'] = _UPLOADREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREQUEST,
  '__module__' : 'upload_pb2'
  # @@protoc_insertion_point(class_scope:upload.UploadRequest)
  })
_sym_db.RegisterMessage(UploadRequest)

UploadReply = _reflection.GeneratedProtocolMessageType('UploadReply', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREPLY,
  '__module__' : 'upload_pb2'
  # @@protoc_insertion_point(class_scope:upload.UploadReply)
  })
_sym_db.RegisterMessage(UploadReply)



_UPLOAD = _descriptor.ServiceDescriptor(
  name='Upload',
  full_name='upload.Upload',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=117,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upload',
    full_name='upload.Upload.Upload',
    index=0,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_UPLOADREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOAD)

DESCRIPTOR.services_by_name['Upload'] = _UPLOAD

# @@protoc_insertion_point(module_scope)
